---
version: '3'
services:
  app:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${DOCKER_COMPOSE_PORT}:3000'
    env_file: .env
    restart: always
