---
version: '3'
services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - '${DOCKER_COMPOSE_PORT}:3000'
    env_file: .env
    restart: always
