---
version: '3.3'
services:
  portfolio_dev:
    container_name: portfolio_dev
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio_dev
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
